# To install numpy !pip install numpy

In [2]:
import numpy as np # np is a alias for numpy, which is a library for numerical computations in Python
print(np.__version__) # to check the version of numpy

2.4.4


# Create numpy array

In [3]:
my_array = np.array([1, 2, 3, 4, 5]) # creating a numpy array from a list
print(my_array) # printing the array
print(type(my_array)) # checking the type of my_array, which should be <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
my_array

array([1, 2, 3, 4, 5])

# array dimensions

In [5]:
matrix = np.array([[1,3,5],[6,8,10]])
matrix

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [6]:
print(matrix.dtype)

int64


In [7]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# How to check dimensions of array?

In [8]:
np.ndim(array3d) 

3

In [9]:
array3d.ndim

3

# How to check rows and columns in a matrix or numpy array?
* shape

In [10]:
array3d.shape

(1, 3, 3)

In [11]:
matrix.shape # 2 is rows and 3 is columns

(2, 3)

# How to create array by using numpy prebuilt functions
* np.zeros
* np.ones

In [12]:
# zeros creates an array filled with zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ones = np.ones((4,5))

In [14]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* np.full()
* Creates an array filled with used custom value, similar to zeros and ones. Wespecify the shape with a tuple and outside the shape tuple we need tomention the value that we want an array of.

In [15]:
full = np.full((4,5),9)
full

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

# Array creation with Random method

In [16]:
# np.random() give uniform distribuion of random vales between 0 and 1
random = np.random.rand(3,4)
random

array([[0.38991645, 0.64651329, 0.92522948, 0.14209178],
       [0.88002796, 0.71248065, 0.41651165, 0.79321948],
       [0.47948156, 0.3468948 , 0.6101824 , 0.33495388]])

In [17]:
# np.random.randn creates an array of the given shape with random values from a standard normal distribution (0,1)
random2 = np.random.randn(5,6)
print(random2)

[[-0.20804722  0.37029503  0.9763039  -0.78126482  0.30772827 -1.14750457]
 [ 0.23316721  0.30164826  1.79686172  1.33312207 -0.51050217  1.00238199]
 [ 0.54990596  0.19913932 -1.2322894  -0.63162523 -1.48367664 -0.77678252]
 [-0.02632361 -0.53387878  0.57119262  0.66434924 -0.90268321  0.28284777]
 [-1.39112168 -0.6790572   0.57263281 -0.41731809 -1.19833169  1.32912139]]


In [23]:
# np.random.randint(start, stop,size)
# it will give values between 1 to 10 and it will give 12 values
random3 = np.random.randint(1,10,12)
random3

array([3, 4, 2, 9, 3, 3, 5, 6, 1, 1, 3, 7], dtype=int32)

* we can also create matrix with np.random.randint

In [19]:
mat = np.random.randint(2,10,(5,6)) # it will give values between 2 to 10 and it will give 5 rows and 6 columns
mat

array([[2, 6, 3, 6, 7, 6],
       [9, 7, 5, 8, 3, 6],
       [2, 6, 2, 9, 7, 5],
       [5, 5, 5, 6, 8, 8],
       [7, 2, 6, 2, 6, 2]], dtype=int32)

In [20]:
a = np.random.randint(0,25,26) # generate a ranodom integer between 0 and 25 or the range we will pass
print(a)

[ 9 24 15  3  5 15  9 21  4 17  9  9  1  7 11 22 18 19  3  7  3  0 24 15
  0 22]


# diff btw random.randint and random_integers

In [21]:
# np.random.random_integer(start,stop,size) 
# import warnings
# warnings.filterwarnings("ignore")

b = np.random.random_integers(2,4,9) # start and end point is inclusive in this function this is the diff between random_integers and randint
b

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10788\2141357976.py:5: DeprecationWarning: This function is deprecated. Please call randint(2, 4 + 1) instead
  b = np.random.random_integers(2,4,9) # start and end point is inclusive in this function this is the diff between random_integers and randint


array([3, 2, 2, 4, 3, 3, 3, 4, 3], dtype=int32)

In [22]:
mat1 = np.random.random_integers(1,10,(5,4)) # can also generate a matrix using random_integers by passing shape of the matrix
mat1

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10788\371211618.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  mat1 = np.random.random_integers(1,10,(5,4)) # can also generate a matrix using random_integers by passing shape of the matrix


array([[ 8, 10,  5,  7],
       [ 5,  5,  6,  1],
       [ 4,  6,  6,  8],
       [ 2,  6,  5, 10],
       [ 4,  7,  1,  8]], dtype=int32)

* np.random.uniform

In [24]:
np.random.uniform(0,1,(4,5))

array([[0.30969832, 0.11718767, 0.77289952, 0.29558736, 0.86750752],
       [0.2721799 , 0.98080645, 0.74524391, 0.79026772, 0.14801158],
       [0.34685545, 0.1448547 , 0.57802695, 0.1644341 , 0.99858618],
       [0.37922578, 0.67270545, 0.76599413, 0.25909345, 0.98187934]])

In [26]:
np.random.uniform(3,4,size=(2,4))

array([[3.64397731, 3.98383131, 3.27211947, 3.61962792],
       [3.5146631 , 3.33130851, 3.28253934, 3.71176491]])

* np.random.choice() * this will pick any number from the array which is already predefined or predicted or formed

In [32]:
b = np.random.randint(4,10,19)
b

array([5, 9, 4, 9, 5, 8, 7, 5, 9, 8, 6, 4, 5, 7, 5, 7, 7, 6, 7],
      dtype=int32)

In [34]:
np.random.choice(b) # this is how choice function works

np.int32(7)

* np.random.normal # this will give (mean,std_dev,size)


In [37]:
np.random.normal(1,7,size=(4,3))

array([[  9.48642002,   9.29270371,  -2.82633744],
       [  8.4549702 ,  -9.06384102,   8.55261009],
       [  8.28084169,   0.94149787, -14.95663831],
       [  9.31279546,  11.90278463,   3.31373281]])

# Attributes of Numpy Arrays
* shape
* reshape


In [40]:
np.random.randint(2,10,8).reshape(2,4) # reshape will arrange a array in a matrix with desired shape

array([[6, 5, 8, 7],
       [7, 8, 2, 6]], dtype=int32)

# Indexing and slicing.

In [45]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# indexing with 1-D Array

data[4] #element at 4th index is 5


np.int64(5)

* indexing and slicing with n-dimensional array

In [51]:
a = [1,2,3,4]
b = [4,5,6,7]
c = [5,7,8,9]
data1 = np.array([a,b,c]) # IN python data structure there is also a method like that called packing and unpacking of list.

In [50]:
data1

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 7, 8, 9]])

* now we have a matrix of 4 by 3 if we want to extract a single element from it or a group of element then we perform slicing to it so that with the given indices the desired data is extracted

In [53]:
# if we want to get the middle dataa like 9 so the value/indexing for row is 2 and for column is 3 so the indexing will be like 2:3
data1[2,3] #[row,column]

np.int64(9)

In [57]:
# if we want a range of data then we give indexing to range or row and column like [a:b,c:d] where a:b is row indexing and c:d is column indexing the our data is extracted or sliced
data1[1:3,1:3] # here the value of row and column is n-1 means 1:4 means 1:3 ONLY

array([[5, 6],
       [7, 8]])

In [58]:
# now performing some fn on a randomly generated matrix

matr = np.random.randint(1,80,size=(4,7))
print(matr)

[[11  5  6 39 73 43 18]
 [52 59 23 51 75 55 16]
 [19  1 20 66 42 48  8]
 [67 50 17 57 53 77 22]]


In [70]:
print(matr.shape," " ,matr.ndim,' ', '\n',matr.reshape(7,4))

(4, 7)   2   
 [[11  5  6 39]
 [73 43 18 52]
 [59 23 51 75]
 [55 16 19  1]
 [20 66 42 48]
 [ 8 67 50 17]
 [57 53 77 22]]


In [71]:
matr

array([[11,  5,  6, 39, 73, 43, 18],
       [52, 59, 23, 51, 75, 55, 16],
       [19,  1, 20, 66, 42, 48,  8],
       [67, 50, 17, 57, 53, 77, 22]], dtype=int32)

In [73]:
# find the elements from the 3rd row and from 5 column by performing slicing
matr[1:4,0:3]

array([[52, 59, 23],
       [19,  1, 20],
       [67, 50, 17]], dtype=int32)