# To install numpy !pip install numpy

In [1]:
import numpy as np # np is a alias for numpy, which is a library for numerical computations in Python
print(np.__version__) # to check the version of numpy

2.3.5


# Create numpy array

In [2]:
my_array = np.array([1, 2, 3, 4, 5]) # creating a numpy array from a list
print(my_array) # printing the array
print(type(my_array)) # checking the type of my_array, which should be <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
my_array

array([1, 2, 3, 4, 5])

# array dimensions

In [10]:
matrix = np.array([[1,3,5],[6,8,10]])
matrix

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [11]:
print(matrix.dtype)

int64


In [19]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# How to check dimensions of array?

In [ ]:
np.ndim(array3d) 

3

In [22]:
array3d.ndim

3

# How to check rows and columns in a matrix or numpy array?
* shape

In [23]:
array3d.shape

(1, 3, 3)

In [25]:
matrix.shape # 2 is rows and 3 is columns

(2, 3)

# How to create array by using numpy prebuilt functions
* np.zeros
* np.ones

In [28]:
# zeros creates an array filled with zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
ones = np.ones((4,5))

In [ ]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* np.full()
* Creates an array filled with used custom value, similar to zeros and ones. Wespecify the shape with a tuple and outside the shape tuple we need tomention the value that we want an array of.

In [36]:
full = np.full((4,5),9)
full

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

# Array creation with Random method

In [46]:
# np.random() give uniform distribuion of random vales between 0 and 1
random = np.random.rand(3,4)
random

array([[0.3622026 , 0.43551483, 0.75578112, 0.09905945],
       [0.74584644, 0.1329792 , 0.87740629, 0.77875674],
       [0.1188506 , 0.40186727, 0.04826986, 0.49027121]])

In [44]:
# np.random.randn creates an array of the given shape with random values from a standard normal distribution (0,1)
random2 = np.random.randn(5,6)
print(random2)

[[ 0.8230224   1.75361739 -0.25921202 -0.26371556  1.2731067   1.09120886]
 [ 0.42086434  1.48531539 -0.07319063  1.44796287 -0.11965524  0.94538013]
 [-1.17471337 -0.05620822  0.92467848 -0.6143855   1.2329439  -0.25155055]
 [-0.28442939  0.5936107  -0.10870311 -0.82335001  0.57892146  0.62982418]
 [-0.14158368  0.35535359  0.84824701 -0.25711964 -0.50782261 -0.83285546]]


In [51]:
# np.random.randint(start, stop,size)
# it will give values between 1 to 10 and it will give 12 values
random3 = np.random.randint(1,10,12)
random3

array([3, 8, 6, 1, 4, 3, 9, 9, 8, 2, 1, 8], dtype=int32)

* we can also create matrix with np.random.randint

In [52]:
mat = np.random.randint(2,10,(5,6)) # it will give values between 2 to 10 and it will give 5 rows and 6 columns
mat

array([[9, 7, 7, 7, 8, 2],
       [2, 6, 5, 5, 2, 6],
       [4, 8, 3, 4, 8, 7],
       [4, 2, 6, 2, 3, 9],
       [7, 5, 8, 5, 2, 8]], dtype=int32)

In [70]:
a = np.random.randint(0,25,26) # generate a ranodom integer between 0 and 25 or the range we will pass
print(a)

[20  8 14 15 20  3 23 15 13 21 21 16 17  5  9  3  0  5  0 17 18  4  2 16
  3  2]


# diff btw random.randint and random_integers

In [77]:
# np.random.random_integer(start,stop,size) 
# import warnings
# warnings.filterwarnings("ignore")

b = np.random.random_integers(2,4,9) # start and end point is inclusive in this function this is the diff between random_integers and randint
b

array([2, 2, 3, 4, 2, 2, 3, 2, 4], dtype=int32)

In [79]:
mat1 = np.random.random_integers(1,10,(5,4)) # can also generate a matrix using random_integers by passing shape of the matrix
mat1

array([[ 9,  1,  5, 10],
       [ 7,  6,  8,  9],
       [ 9, 10,  3,  9],
       [ 7,  7, 10,  2],
       [ 7,  9,  9,  4]], dtype=int32)