# To install numpy !pip install numpy

In [2]:
import numpy as np # np is a alias for numpy, which is a library for numerical computations in Python
print(np.__version__) # to check the version of numpy

2.4.4


# Create numpy array

In [3]:
my_array = np.array([1, 2, 3, 4, 5]) # creating a numpy array from a list
print(my_array) # printing the array
print(type(my_array)) # checking the type of my_array, which should be <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
my_array

array([1, 2, 3, 4, 5])

# array dimensions

In [5]:
matrix = np.array([[1,3,5],[6,8,10]])
matrix

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [6]:
print(matrix.dtype)

int64


In [7]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# How to check dimensions of array?

In [8]:
np.ndim(array3d) 

3

In [9]:
array3d.ndim

3

# How to check rows and columns in a matrix or numpy array?
* shape

In [10]:
array3d.shape

(1, 3, 3)

In [11]:
matrix.shape # 2 is rows and 3 is columns

(2, 3)

# How to create array by using numpy prebuilt functions
* np.zeros
* np.ones

In [12]:
# zeros creates an array filled with zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ones = np.ones((4,5))

In [14]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* np.full()
* Creates an array filled with used custom value, similar to zeros and ones. Wespecify the shape with a tuple and outside the shape tuple we need tomention the value that we want an array of.

In [15]:
full = np.full((4,5),9)
full

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

# Array creation with Random method

In [16]:
# np.random() give uniform distribuion of random vales between 0 and 1
random = np.random.rand(3,4)
random

array([[0.69318763, 0.2821896 , 0.21827443, 0.19181917],
       [0.534256  , 0.73978134, 0.22878938, 0.2035788 ],
       [0.10913214, 0.03470285, 0.81347881, 0.27932991]])

In [17]:
# np.random.randn creates an array of the given shape with random values from a standard normal distribution (0,1)
random2 = np.random.randn(5,6)
print(random2)

[[-0.11226105  1.98325605  0.95537538  1.15358328 -0.27052452 -0.84902829]
 [ 1.18983164  0.04574653 -1.15183084 -1.27452402  1.04448355 -0.15992911]
 [ 1.89205303 -2.33142215  3.1053353  -1.91173374 -1.12972467  0.10721746]
 [ 0.22694052 -1.25105821  1.12592801 -1.29474986 -0.25315674 -0.70674012]
 [-0.95332667  0.16712914 -0.14779896 -1.6236123   2.52517795  1.64277498]]


In [18]:
# np.random.randint(start, stop,size)
# it will give values between 1 to 10 and it will give 12 values
random3 = np.random.randint(1,10,12)
random3

array([9, 6, 5, 6, 2, 4, 9, 1, 3, 5, 5, 3], dtype=int32)

* we can also create matrix with np.random.randint

In [19]:
mat = np.random.randint(2,10,(5,6)) # it will give values between 2 to 10 and it will give 5 rows and 6 columns
mat

array([[2, 2, 2, 3, 6, 4],
       [3, 5, 3, 2, 2, 8],
       [5, 8, 9, 2, 9, 4],
       [6, 7, 7, 8, 5, 8],
       [6, 7, 8, 5, 7, 5]], dtype=int32)

In [20]:
a = np.random.randint(0,25,26) # generate a ranodom integer between 0 and 25 or the range we will pass
print(a)

[18  8 24 16 11  2 16 23 20  8  2 17  4 12  5  7  5 15 18  2 16 17  5  7
  2 14]


# diff btw random.randint and random_integers

In [21]:
# np.random.random_integer(start,stop,size) 
# import warnings
# warnings.filterwarnings("ignore")

b = np.random.random_integers(2,4,9) # start and end point is inclusive in this function this is the diff between random_integers and randint
b

C:\Users\ASUS\AppData\Local\Temp\ipykernel_6064\2141357976.py:5: DeprecationWarning: This function is deprecated. Please call randint(2, 4 + 1) instead
  b = np.random.random_integers(2,4,9) # start and end point is inclusive in this function this is the diff between random_integers and randint


array([4, 2, 4, 4, 4, 3, 4, 2, 3], dtype=int32)

In [22]:
mat1 = np.random.random_integers(1,10,(5,4)) # can also generate a matrix using random_integers by passing shape of the matrix
mat1

C:\Users\ASUS\AppData\Local\Temp\ipykernel_6064\371211618.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  mat1 = np.random.random_integers(1,10,(5,4)) # can also generate a matrix using random_integers by passing shape of the matrix


array([[ 6,  9,  3, 10],
       [ 7,  8,  2,  4],
       [ 7,  7,  9,  9],
       [ 6,  7,  7,  4],
       [ 1,  1,  8,  8]], dtype=int32)

* np.random.uniform

In [23]:
np.random.uniform(0,1,(4,5))

array([[0.65114203, 0.54998392, 0.35805134, 0.5726269 , 0.44003978],
       [0.83892323, 0.70566683, 0.98502972, 0.46166038, 0.81295285],
       [0.69652237, 0.61114446, 0.90122804, 0.04462132, 0.7010394 ],
       [0.34303798, 0.22337751, 0.61513538, 0.89257509, 0.45283448]])

In [24]:
np.random.uniform(3,4,size=(2,4))

array([[3.04937474, 3.59731694, 3.89075784, 3.01688342],
       [3.43736432, 3.55434877, 3.42477966, 3.20270493]])

* np.random.choice() * this will pick any number from the array which is already predefined or predicted or formed

In [25]:
b = np.random.randint(4,10,19)
b

array([6, 4, 6, 7, 6, 7, 9, 4, 6, 5, 4, 7, 7, 5, 4, 6, 7, 9, 9],
      dtype=int32)

In [26]:
np.random.choice(b) # this is how choice function works

np.int32(7)

* np.random.normal # this will give (mean,std_dev,size)


In [27]:
np.random.normal(1,7,size=(4,3))

array([[ -4.16970812,   9.9397551 ,  12.8883355 ],
       [  1.87470036,   6.78662721,   5.90233936],
       [-12.20803858,   3.87271125,   7.93188705],
       [  0.16508031,   3.93460981,  -2.68097514]])

# Attributes of Numpy Arrays
* shape
* reshape


In [28]:
np.random.randint(2,10,8).reshape(2,4) # reshape will arrange a array in a matrix with desired shape

array([[9, 4, 4, 4],
       [2, 4, 2, 2]], dtype=int32)

# Indexing and slicing.

In [29]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# indexing with 1-D Array

data[4] #element at 4th index is 5


np.int64(5)

* indexing and slicing with n-dimensional array

In [31]:
a = [1,2,3,4]
b = [4,5,6,7]
c = [5,7,8,9]
data1 = np.array([a,b,c]) # IN python data structure there is also a method like that called packing and unpacking of list.

In [32]:
data1

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 7, 8, 9]])

* now we have a matrix of 4 by 3 if we want to extract a single element from it or a group of element then we perform slicing to it so that with the given indices the desired data is extracted

In [33]:
# if we want to get the middle dataa like 9 so the value/indexing for row is 2 and for column is 3 so the indexing will be like 2:3
data1[2,3] #[row,column]

np.int64(9)

In [34]:
# if we want a range of data then we give indexing to range or row and column like [a:b,c:d] where a:b is row indexing and c:d is column indexing the our data is extracted or sliced
data1[1:3,1:3] # here the value of row and column is n-1 means 1:4 means 1:3 ONLY

array([[5, 6],
       [7, 8]])

In [35]:
# now performing some fn on a randomly generated matrix

matr = np.random.randint(1,80,size=(4,7))
print(matr)

[[42 12  3 49  4 49 75]
 [57 11 38 63 13 31 75]
 [45 15 64 39 47 14 47]
 [19 66 17 31 17 49 52]]


In [36]:
print(matr.shape," " ,matr.ndim,' ', '\n',matr.reshape(7,4))

(4, 7)   2   
 [[42 12  3 49]
 [ 4 49 75 57]
 [11 38 63 13]
 [31 75 45 15]
 [64 39 47 14]
 [47 19 66 17]
 [31 17 49 52]]


In [37]:
matr

array([[42, 12,  3, 49,  4, 49, 75],
       [57, 11, 38, 63, 13, 31, 75],
       [45, 15, 64, 39, 47, 14, 47],
       [19, 66, 17, 31, 17, 49, 52]], dtype=int32)

In [38]:
# find the elements from the 3rd row and from 5 column by performing slicing
matr[1:4,0:3]

array([[57, 11, 38],
       [45, 15, 64],
       [19, 66, 17]], dtype=int32)

# data manipulation with arrays
## stacking array
* hstack 
* vstack
* column stack

* vstack in numpy
 np.vstack is a function provided by the NumPy library in Python for verticalstacking of arrays. Vertical stacking, or "vstack," refers to stacking arrays ontop of each other along the rows. It combines arrays by adding rows,effectively increasing the number of rows in the resulting array.

In [39]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
verticalstack = np.vstack((array1,array2))


In [43]:
verticalstack # now we can perform various other fun on it like shape reshape etc.

array([[1, 2, 3],
       [4, 5, 6]])

* column stack :->
Column stacking, often referred to as "column_stack," is the process ofstacking arrays side by side along columns to create a new array. This operation is useful when you want to combine multiple 1D arrays or lists into a 2D array, where each original array becomes a column in the resulting 2Darray.

In [46]:
np.column_stack([array1,array2])


array([[1, 4],
       [2, 5],
       [3, 6]])

*  Horizontal stacking, often referred to as hstack, is the process of combiningmultiple arrays horizontally along the columns. This means that the arrays arestacked side by side, effectively extending the number of columns in theresulting array.

In [47]:
np.hstack([array1,array2])

array([1, 2, 3, 4, 5, 6])