# To install numpy !pip install numpy

In [1]:
import numpy as np # np is a alias for numpy, which is a library for numerical computations in Python
print(np.__version__) # to check the version of numpy

2.3.5


# Create numpy array

In [2]:
my_array = np.array([1, 2, 3, 4, 5]) # creating a numpy array from a list
print(my_array) # printing the array
print(type(my_array)) # checking the type of my_array, which should be <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
my_array

array([1, 2, 3, 4, 5])

# array dimensions

In [10]:
matrix = np.array([[1,3,5],[6,8,10]])
matrix

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [11]:
print(matrix.dtype)

int64


In [19]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# How to check dimensions of array?

In [ ]:
np.ndim(array3d) 

3

In [22]:
array3d.ndim

3

# How to check rows and columns in a matrix or numpy array?
* shape

In [23]:
array3d.shape

(1, 3, 3)

In [25]:
matrix.shape # 2 is rows and 3 is columns

(2, 3)

# How to create array by using numpy prebuilt functions
* np.zeros
* np.ones

In [28]:
# zeros creates an array filled with zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
ones = np.ones((4,5))

In [ ]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* np.full()
* Creates an array filled with used custom value, similar to zeros and ones. Wespecify the shape with a tuple and outside the shape tuple we need tomention the value that we want an array of.

In [36]:
full = np.full((4,5),9)
full

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])